### ISSUE TITLE
Folders are uploading twice or thrice under root as well as in AppID

### ISSUE THREAD

**Issue by AchalaSB** [KIPFoundation/kfs#167] opened 2019-04-24 05:31 UTC
Currently when folder is getting uploaded it upload once and able to remove that folder.

But sometimes its uploading twice or thrice. In that case, one folder shows as empty and other contains files but unable to remove both folders

**Comment by 0zAND1z** [comment] 2019-04-28 10:26
@akshitababel , would it be possible for us to check for duplication in entries before we add them to sitemap and explorer? 

@its-VSP , please let us know your thoughts on this approach. Cheers.

**Comment by its-VSP** [comment] 2019-04-30 05:12
I think until and unless we discover what is the thing that puts us in this context , we should not put checks.

**Comment by 0zAND1z** [comment] 2019-05-08 08:54
Agreed @its-VSP. 

@akshitababel  - please let us know when you are done analyzing the situation along with a root cause analysis.

**Comment by its-VSP** [comment] 2019-06-17 13:21
Couldn't able to reproduce this issue after FILE API got stablized , so closing this issue

**Closed by its-VSP** 2019-06-17 13:21 UTC
Labels: bug
